/** 国家(英文) → 大洲，用于干扰项「同大洲」 */
const COUNTRY_EN_TO_CONTINENT: Record<string, string> = {
  China: 'Asia',
  Japan: 'Asia',
  'South Korea': 'Asia',
  Thailand: 'Asia',
  Singapore: 'Asia',
  India: 'Asia',
  Malaysia: 'Asia',
  Indonesia: 'Asia',
  Vietnam: 'Asia',
  Myanmar: 'Asia',
  Taiwan: 'Asia',
  UAE: 'Asia',
  Israel: 'Asia',
  Turkey: 'Asia',
  Georgia: 'Asia',
  Azerbaijan: 'Asia',
  Russia: 'Europe',
  'Czech Republic': 'Europe',
  Denmark: 'Europe',
  UK: 'Europe',
  France: 'Europe',
  Germany: 'Europe',
  Italy: 'Europe',
  Spain: 'Europe',
  Netherlands: 'Europe',
  Belgium: 'Europe',
  Ireland: 'Europe',
  Greece: 'Europe',
  Switzerland: 'Europe',
  Sweden: 'Europe',
  Poland: 'Europe',
  Portugal: 'Europe',
  Austria: 'Europe',
  Hungary: 'Europe',
  Croatia: 'Europe',
  Estonia: 'Europe',
  Latvia: 'Europe',
  'North Macedonia': 'Europe',
  Malta: 'Europe',
  Cyprus: 'Europe',
  Bosnia: 'Europe',
  Serbia: 'Europe',
  Albania: 'Europe',
  Egypt: 'Africa',
  Ethiopia: 'Africa',
  'South Africa': 'Africa',
  Kenya: 'Africa',
  Morocco: 'Africa',
  Tanzania: 'Africa',
  Rwanda: 'Africa',
  Tunisia: 'Africa',
  USA: 'North America',
  Canada: 'North America',
  Mexico: 'North America',
  Brazil: 'South America',
  Argentina: 'South America',
  Colombia: 'South America',
  Peru: 'South America',
  Cuba: 'North America',
  Uruguay: 'South America',
  Panama: 'North America',
  Australia: 'Oceania',
  Maldives: 'Asia',
  Mongolia: 'Asia',
};

export function getContinent(countryEn: string): string {
  return COUNTRY_EN_TO_CONTINENT[countryEn] ?? 'Other';
}
